from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import StreamingResponse, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import yt_dlp
import yt_dlp.version
import requests
import urllib.parse
import urllib3
import os
import time
import logging
import traceback
import tempfile

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("yt-dlp-downloader")

# Ensure writable directories on Vercel's read-only serverless filesystem.
# Vercel functions only permit writes inside `/tmp`. Overriding the XDG environment
# variables ensures that any cache, data, or config files generated by yt-dlp 
# are written to /tmp without permission crashes.
tmp_dir = tempfile.gettempdir()
os.environ['XDG_CACHE_HOME'] = os.path.join(tmp_dir, 'yt_dlp_cache')
os.environ['XDG_DATA_HOME'] = os.path.join(tmp_dir, 'yt_dlp_data')
os.environ['XDG_CONFIG_HOME'] = os.path.join(tmp_dir, 'yt_dlp_config')

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

app = FastAPI()

# Enable CORS so frontend can easily hit these endpoints
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class DownloadRequest(BaseModel):
    url: str
    format: str

@app.post("/api/download")
def get_download_info(req: DownloadRequest):
    url = req.url
    format_type = req.format
    
    if not url:
        return JSONResponse(status_code=400, content={"success": False, "error": "URL is required"})
        
    start_time = time.time()
    temp_cookies_file = None
    
    # Track execution details for audit logs
    video_id = "unknown"
    successful_client = None
    last_exception = None
    client_errors = {}
    info = None
    
    # Try to pre-extract video ID from standard YouTube URL formats for logging context.
    try:
        parsed_url = urllib.parse.urlparse(url)
        if parsed_url.netloc in ('youtu.be', 'www.youtu.be'):
            video_id = parsed_url.path.lstrip('/')
        elif 'youtube.com' in parsed_url.netloc or 'youtube-nocookie.com' in parsed_url.netloc:
            if parsed_url.path == '/watch':
                query = urllib.parse.parse_qs(parsed_url.query)
                video_id = query.get('v', ['unknown'])[0]
            elif parsed_url.path.startswith(('/embed/', '/v/', '/shorts/')):
                video_id = parsed_url.path.split('/')[2]
    except Exception as e:
        logger.warning(f"Could not parse video ID from URL before extraction: {e}")

    # Log current yt-dlp version being used
    yt_dlp_version = getattr(yt_dlp.version, '__version__', 'unknown')
    logger.info(f"Initiating extraction process. yt-dlp version: {yt_dlp_version}, URL: {url}")

    # Set up temporary cookies file if passed via environment variable (optional fallback helper)
    cookies_content = os.environ.get("YOUTUBE_COOKIES")
    if cookies_content:
        try:
            fd, temp_cookies_file = tempfile.mkstemp(suffix=".txt", prefix="cookies_")
            with os.fdopen(fd, 'w') as f:
                f.write(cookies_content)
        except Exception as ce:
            logger.error(f"Failed to create temp cookies file: {ce}")

    # Set up environment helper values
    po_token = os.environ.get("YOUTUBE_PO_TOKEN")
    visitor_data = os.environ.get("YOUTUBE_VISITOR_DATA")
    proxy = os.environ.get("YOUTUBE_PROXY")

    # We sequentially fallback across multiple client types:
    # 1. 'android' (very high success rate, bypasses most desktop bot-checks)
    # 2. 'ios' (highly trusted mobile client, sometimes requires PO token)
    # 3. 'tv' (often has relaxed signature requirements, ignores many desktop restrictions)
    # 4. 'web' (standard client, desktop-friendly fallback)
    clients = ['android', 'ios', 'tv', 'web']

    try:
        for client in clients:
            client_start_time = time.time()
            logger.info(f"Attempting metadata extraction with client '{client}' for video ID '{video_id}'")
            
            # Formulate extractor arguments dictionary (standard formatting for yt-dlp Python API)
            client_extractor_args = {
                'client': [client]
            }
            
            # Browser-generated PO Tokens are specific to the web client. We only apply the 
            # YOUTUBE_PO_TOKEN and YOUTUBE_VISITOR_DATA when attempting the 'web' client.
            if client == 'web' and po_token:
                # Clean prefix from the token value if present
                if po_token.startswith("po_token="):
                    po_token_val = po_token.replace("po_token=", "", 1)
                else:
                    po_token_val = po_token
                
                # Ensure the web.gvs+ prefix is present for the web client
                if not po_token_val.startswith("web.gvs+"):
                    po_token_val = f"web.gvs+{po_token_val}"
                    
                client_extractor_args['po_token'] = [po_token_val]
                
                # Apply matching visitor_data if available to complete the integrity verification session
                if visitor_data:
                    if visitor_data.startswith("visitor_data="):
                        visitor_data_val = visitor_data.replace("visitor_data=", "", 1)
                    else:
                        visitor_data_val = visitor_data
                    client_extractor_args['visitor_data'] = [visitor_data_val]
                
            # Base options configured to maximize success on Vercel without external auth/cookies/proxies
            ydl_opts = {
                'quiet': True,
                'no_warnings': True,
                'nocheckcertificate': True,
                # Task 8: Test metadata extraction first with skip_download=True.
                # In serverless context, we never save the full files to local disk to keep execution times & memory low.
                'skip_download': True,
                # Task 5: Force IPv4 by binding to 0.0.0.0. This prevents IPv6 range blocks which Vercel commonly encounters.
                'source_address': '0.0.0.0',
                # Task 2: Configure JavaScript runtimes. yt-dlp uses JS runtimes to solve signature and n-parameter challenges.
                # Adding all supported options allows yt-dlp to pick whatever is available (Node.js on Vercel).
                'js_runtimes': {
                    'node': {},
                    'deno': {},
                    'bun': {},
                    'quickjs': {}
                },
                # Task 2: Enable automatic download and caching of latest challenge solver scripts from GitHub.
                'remote_components': {'ejs:github'},
                # Force caching to the writable /tmp path to prevent permission crashes.
                'cachedir': os.path.join(tmp_dir, 'yt_dlp_cache'),
                'extractor_args': {
                    'youtube': client_extractor_args
                },
                'format': 'bestaudio/best' if format_type == 'mp3' else 'best[ext=mp4]/best'
            }

            if proxy:
                ydl_opts['proxy'] = proxy
            if temp_cookies_file:
                ydl_opts['cookiefile'] = temp_cookies_file

            # Task 4: For the 'web' client, set a modern, realistic browser User-Agent and accompanying headers
            # to match real client request profiles and avoid bot-detection.
            # We avoid applying these headers to mobile/tv clients to prevent UA-to-client mismatch blocks.
            if client == 'web':
                ydl_opts['http_headers'] = {
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
                    'Accept-Language': 'en-US,en;q=0.9',
                    'Sec-Fetch-Mode': 'navigate',
                    'Sec-Fetch-User': '?1',
                    'Sec-Fetch-Dest': 'document',
                }

            try:
                with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                    # Extract metadata only (download=False)
                    info = ydl.extract_info(url, download=False)
                
                # If extraction succeeded, record metadata details and exit loop
                successful_client = client
                duration = time.time() - client_start_time
                if info and 'id' in info:
                    video_id = info['id']
                logger.info(f"Extraction SUCCEEDED with client '{client}' for video ID '{video_id}' in {duration:.2f} seconds")
                break
            except Exception as e:
                duration = time.time() - client_start_time
                last_exception = e
                # Get the first line of the error message to keep it readable
                err_clean = str(e).split('\n')[0]
                client_errors[client] = err_clean
                logger.warning(f"Extraction FAILED with client '{client}' for video ID '{video_id}' in {duration:.2f} seconds. Error: {str(e)}")
                # Continue loop to fallback on next client

        if not successful_client:
            total_duration = time.time() - start_time
            err_msg = str(last_exception) or "Unknown extraction failure"
            details = "; ".join([f"{k}: {v}" for k, v in client_errors.items()])
            logger.error(f"All player clients failed. Total duration: {total_duration:.2f} seconds. Errors: {details}")
            
            # Print full trace internally for debug auditing
            logger.error(f"Internal traceback:\n{traceback.format_exc()}")

            # Task 9: Detect bot-detection signatures and return clean messages
            bot_keywords = [
                "confirm you're not a bot", 
                "sign in to confirm", 
                "not available on this app", 
                "too many requests", 
                "429", 
                "login required",
                "confirm your age",
                "verify your account"
            ]
            
            if any(kw in err_msg.lower() for kw in bot_keywords):
                user_error = (
                    "YouTube has temporarily rate-limited or blocked this request. "
                    f"Please try again or try another format. (Details: {details})"
                )
                return JSONResponse(status_code=403, content={"success": False, "error": user_error})
            
            # Check for invalid URL or private video errors
            invalid_keywords = ["not a valid url", "invalid url", "private video", "video unavailable", "does not exist"]
            if any(kw in err_msg.lower() for kw in invalid_keywords):
                user_error = f"The video is private, unavailable, or the URL is invalid. (Details: {details})"
            else:
                user_error = f"Failed to extract video details. (Details: {details})"
                
            return JSONResponse(status_code=400, content={"success": False, "error": user_error})

        # Process the successfully extracted metadata
        if not info:
            return JSONResponse(status_code=500, content={"success": False, "error": "Failed to retrieve video metadata"})

        # Handle playlist structure
        if 'entries' in info or info.get('_type') == 'playlist':
            entries = []
            raw_entries = info.get('entries', [])
            for entry in raw_entries:
                if entry:
                    entries.append({
                        'title': entry.get('title') or "Untitled Video",
                        'url': entry.get('webpage_url') or entry.get('url'),
                        'duration': entry.get('duration') or 0,
                    })
            return {
                'success': True,
                'isPlaylist': True,
                'title': info.get('title') or "Playlist",
                'entries': entries
            }
        
        # Process single video stream URL selection
        title = info.get('title', 'download')
        clean_title = "".join(c for c in title if c.isalnum() or c in "._- ").strip()
        if not clean_title:
            clean_title = "download"
            
        stream_url = info.get('url')
        if not stream_url and 'formats' in info:
            formats = [f for f in info.get('formats', []) if f.get('url')]
            if formats:
                stream_url = formats[-1].get('url')
                
        if not stream_url:
            return JSONResponse(status_code=400, content={"success": False, "error": "No direct streaming URL found"})
            
        ext = info.get('ext', 'mp4')
        if format_type == 'mp3':
            ext = 'mp3'
            
        filename = f"{clean_title}.{ext}"
        size = info.get('filesize') or info.get('filesize_approx') or 0
        
        # Quick fallback HEAD request if file size metadata is missing
        if size == 0:
            try:
                head_res = requests.head(stream_url, headers={
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
                }, timeout=5)
                if head_res.status_code in (200, 206):
                    size = int(head_res.headers.get('Content-Length', 0))
            except Exception:
                pass
        
        # Proxy streams to bypass client CORS restrictions and Vercel IP blocks
        need_proxy = True
        http_headers = info.get('http_headers', {})
        
        total_duration = time.time() - start_time
        logger.info(f"Extraction pipeline completed successfully in {total_duration:.2f} seconds. Client used: {successful_client}")

        return {
            'success': True,
            'isPlaylist': False,
            'url': stream_url,
            'filename': filename,
            'size': size,
            'ext': ext,
            'needProxy': need_proxy,
            'httpHeaders': http_headers
        }
            
    except Exception as global_ex:
        logger.error(f"Global download api exception: {str(global_ex)}\n{traceback.format_exc()}")
        return JSONResponse(status_code=500, content={"success": False, "error": "An unexpected server error occurred"})
    finally:
        if temp_cookies_file and os.path.exists(temp_cookies_file):
            try:
                os.remove(temp_cookies_file)
            except Exception:
                pass

import json

@app.get("/api/proxy")
def proxy_stream(
    url: str = Query(..., description="The direct media URL to proxy"),
    start: int = Query(None, description="Start byte"),
    end: int = Query(None, description="End byte"),
    headers_json: str = Query(None, description="JSON string of custom headers to pass")
):
    try:
        # Default header to look like standard Chrome browser
        req_headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        }
        
        if headers_json:
            try:
                import urllib.parse
                decoded_json = urllib.parse.unquote(headers_json)
                custom_headers = json.loads(decoded_json)
                req_headers.update(custom_headers)
            except Exception:
                pass
                
        # Support chunk-based range queries (Task 10: keeps memory footprint small and operations brief)
        if start is not None and end is not None:
            req_headers["Range"] = f"bytes={start}-{end}"
            
        resp = requests.get(url, headers=req_headers, stream=True, timeout=12, verify=False)
        
        if resp.status_code not in (200, 206):
            raise HTTPException(status_code=resp.status_code, detail=f"Failed to fetch media chunk: {resp.status_code}")
            
        def generate():
            # Stream small 16KB blocks to prevent memory accumulation in serverless environment
            for chunk in resp.iter_content(chunk_size=16384):
                yield chunk
                
        response_headers = {
            "Content-Range": resp.headers.get("Content-Range", ""),
            "Content-Length": resp.headers.get("Content-Length", ""),
            "Content-Type": resp.headers.get("Content-Type", "application/octet-stream"),
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Expose-Headers": "Content-Range, Content-Length, Content-Type, Accept-Ranges",
            "Accept-Ranges": "bytes"
        }
        
        return StreamingResponse(
            generate(),
            status_code=resp.status_code,
            headers={k: v for k, v in response_headers.items() if v}
        )
    except HTTPException:
        raise
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))
